### PR TITLE
Remove SASS deprecation warnings

### PR DESCRIPTION
**Pull request by desko27**
As stated in #528, [node-sass](https://www.npmjs.com/package/node-sass) is deprecated in favor of [sass](https://www.npmjs.com/package/sass). This is causing lots of warnings (due to [this breaking change](https://sass-lang.com/documentation/breaking-changes/slash-div)) in projects who consume keen-ui _uncompiled SASS components_ (directly from keen-ui/src/*) and already got rid of node-sass.

So here:

- [x] node-sass is removed in favor of sass
- [x] All deprecation warnings are fixed the recommended way

But releasing this means every project who's still trapped in node-sass _AND imports the original SASS components_ (directly from keen-ui/src/*) will not be able to update keen-ui without having to get rid of node-sass too, since new sass modules (i.e. math.div) are not backwards compatible with node-sass.

In return, projects who import the compiled components (most of users to my understanding) or those who import the uncompiled SASS components but already got rid of node-sass, will flawlessly update keen-ui.

### CODE REVIEW

**Comment by JosephusPaye** [comment]
Thanks!

The backward compatibility issue is an interesting one. Perhaps this can be released with a tag in the version, for those who have made the switch.

**Comment by desko27** [comment]
The tag thing seems good to me. How can I help here?

**Comment by desko27** [comment]
Adding a bit more detail on this as I missed an important point (I updated the PR description to reflect it).

### Summary of story

We're importing the _uncompiled SASS components_ for SASS var customization purposes. That's what's causing the SASS warnings. But importing the named exports just from `keen-ui` is not causing SASS warnings as those components are actually CSS.

### Actual breaking changes

Given that, the users who would receive a "breaking change" from this PR would be the ones who are already importing the _uncompiled SASS components_ directly from `keen-ui/src/*` like us, and still didn't get rid of node-sass.

**Comment by olsgreen** [comment]
@desko27 Nice work, our build screens look much nicer now!

@JosephusPaye Can we get this merged, if you are concerned over the backwards compatibility and want to stay true to semantics just bump the major? Also, would be great to chat to you about the future of this project. We've had great use out of it for a number of years now, I'd hate to see it not move forward, but also realise that you have other commitments. We may be able to help in a few different ways, please just reach out to me.

**Comment by JosephusPaye** [comment]
Hi all, I'll try to get this merged and released soon.

@olsgreen Happy to have a chat about this. I'd love to see the library continue to evolve and be maintained, as I currently use it in production projects myself.

**Comment by JosephusPaye** [comment]
Released in https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.4.0

**Pull request merged**
