### PR TITLE
fixes issue #144 - undefined error in startRipple method

### PR DESCRIPTION
**Pull request by stbaer**

### CODE REVIEW

**Comment by JonasDoebertin** [comment]
Running into the same issue as outlined in #144 and #146.

Having this fix in the next release would be awesome!

**Comment by JosephusPaye** [comment]
Hi @stbaer, 

Thanks for the pull, this will be merged in v1.0.

**Comment by Rob-pw** [comment]
Can we prioritise this? It's a small fix and would make debugging somewhat nice again.

**Comment by JonasDoebertin** [comment]
I second this! Would be really nice to get a quick v0.8.10 release with this fix.

**Comment by JosephusPaye** [comment]
This fix has was added for v1.0.

**Comment by JosephusPaye** [comment]
[v1.0.0](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.0.0) has been released with this fix, and more: https://josephuspaye.github.io/Keen-UI/1.0.0.

**Comment by brickgale** [comment]
Is there a fix for this on v0.8.9?

**Pull request closed without merging**
