### PR TITLE
first set of a e2e tests(close #216)

### LINKED ISSUE #216: e2e tests
Keen-UI is a large set of components with complex logic.
I propose to write e2e tests and setup CI on `travis` or `appveyor`.
I can do this using [testcafe](http://github.com/devexpress/testcafe).
What do you think about this?

### PR DESCRIPTION
**Pull request by miherlosev**

### CODE REVIEW

**Comment by JosephusPaye** [comment]
Thanks for the pull @miherlosev,

It looks good, I'll pull it down and try it when I get some time.

**Comment by JosephusPaye** [comment]
Hi @miherlosev,

Thanks for the work here. Is it possible for you to resubmit this pull request against the `next` branch?

That's where development is happening for the next release.

**Comment by miherlosev** [comment]
Done #271

**Comment by JosephusPaye** [comment]
Closing for https://github.com/JosephusPaye/Keen-UI/pull/271.

**Pull request closed without merging**
