### PR TITLE
Adding events for autocomplete component

### PR DESCRIPTION
**Pull request by rowanwins**
Gday @JosephusPaye 

Here is the first cut of adding some events for the autocomplete component. 

I also picked up a small bug in the search method where it was converting everything to lowercase however this should only happen on strings, so I've thrown in a quick type check there.

I've also updated the docs.

Cheers
Rowan

### CODE REVIEW

**Comment by rowanwins** [comment]
Ps  sorry Im not sure how I've managed to include all your old commits in mine :(

**Comment by JosephusPaye** [comment]
Thanks for the pull, I will have a look at it soon and let you know what I think. Busy at the moment with work on other projects.

**Comment by JosephusPaye** [comment]
Hi @rowanwins,

Had trouble merging your pull due to merge conflicts. However, I was able to include all of your suggestions. See this commit: https://github.com/JosephusPaye/Keen-UI/commit/b6513198d1112b3dca6b4c0953021df2129e4ac9

**Comment by rowanwins** [comment]
Awesome, thanks @JosephusPaye

**Pull request closed without merging**
