### PR TITLE
Keen UI based on vue@2.0x

### PR DESCRIPTION
**Pull request by LucasIcarus**
Just finished about all components and pass the docs as test...

Notice that code style hasn't been justify so this pr couldn't been merged for now..  I will commit some changes soon..

Delete the RadioGroup and make Radio replace it... 3-level two way prop is too complicated to apply for vue2.0.

And many other changes...  Meanwhile, I create a work-flow repo for keen-ui's ssr dev.. 

checkout a new branch first maybe?

### CODE REVIEW

**Comment by JosephusPaye** [comment]
@LucasIcarus Good work here. I will find some time to go through the diff and let you know what I think.

**Comment by leftstick** [comment]
Nice to hear!!

I am curious that how the event work with `$broadcast` in new version.  Cannot wait to see it!^^

**Comment by benjdl** [comment]
Hi @LucasIcarus @JosephusPaye, is the PR ready to be merged ? Vue.js 2.0.0 just arrived yesterday ! :+1:

**Comment by JosephusPaye** [comment]
Not yet, but I'm also working on the Vue 2.0 version, with many ideas taken from the great work done here by @LucasIcarus.

**Comment by HenriqueMatias** [comment]
Hi,
I'm crazy to see it!!!
How can i help with the migration?

**Comment by stbaer** [comment]
Good news @JosephusPaye - keeping the progress public an let the community help might even speed things up ;)

**Comment by LucasIcarus** [comment]
@JosephusPaye  

Sorry for the delay...  I will modify the code style this day and maybe new a branch or for merge this pr and others after Vue 2.0 is released?

**Comment by LucasIcarus** [comment]
@JosephusPaye 

Semicolon thing is done, and I update vue to 2.0.1 and run 'test' by build:docs... works fine in chrome...(stylus style is uncomplete yet)

Merge this in a dev or next branch and release some simple components then works on others together?

**Comment by kristianmandrup** [comment]
When can we expect to see Vue2 support released in the wild!?

**Comment by LucasIcarus** [comment]
@JosephusPaye 

I notice the next branch has been created and need I re-pr this or close it?

**Comment by juppdes** [comment]
Please, can help me ?

err install

**Comment by JosephusPaye** [comment]
Hey @LucasIcarus,

I have made a lots of changes to the docs structure and the build system in preparation for v1. As a result, it's harder to do a direct merge.

However, I'm adapting a lot of your work here and I suggest that you keep the PR open until then.

Thank you!

**Comment by LucasIcarus** [comment]
@JosephusPaye 

OK, and is there any work I can do for the next branch?

**Comment by dts** [comment]
I've had a hard time getting this to work for me, I keep getting "strict mode" errors in relation to the `with()` calls that are in the template functions.

**Comment by LucasIcarus** [comment]
@dts 

`with()` is a func named with or keyword `with`?

keyword `with` is banned in 'strict mode' and why use it?

**Comment by dts** [comment]
See the vue-template-compiler description (https://www.npmjs.com/package/vue-template-compiler)

> Note the returned function code uses with and thus cannot be used in strict mode code.

I'm not sure why the vue template compiler uses 'with', but I'm fairly certain they're talking about the keyword (which kinda looks like a function).

**Comment by EmilMoe** [comment]
No stress, but what's your timeframe for KeenUI Vue2?

**Comment by juppdes** [comment]
Without making pressure, but already doing, there is already some forecast?

**Comment by kristianmandrup** [comment]
There is already vue-materialize which is Vue2 compatible

**Comment by michaelmior** [comment]
I believe [material-components](https://github.com/appcomponents/material-components) also works with Vue 2.x if people are looking for alternatives.

**Comment by EmilMoe** [comment]
Material Components looks okay, vue-materialize looks like a half hearted project to be honest.

**Comment by juppdes** [comment]
https://github.com/appcomponents/material-components is not ready for Vue 2.x..

**Comment by EmilMoe** [comment]
I realised that as well

**Comment by JosephusPaye** [comment]
Hello guys,

I am currently busy with university work at the moment, and will be until 4 weeks from now when my exams will be done. 

Until then, the only time I have to work on this is weekends and I can't promise anything in the next 4 weeks.

**Comment by michaelmior** [comment]
@juppdes @EmilMoe Sorry about that. Obviously I was mistaken. Looks like Keen-UI is pretty close :)

**Comment by HenriqueMatias** [comment]
hi @LucasIcarus ,

couldn't we use a advanced branch where vue2 is working?

**Comment by LucasIcarus** [comment]
@HenriqueMatias 

The next branch in this repo can work I think...  It just missing some doc details and may need some  small bug fixing in actually using.

**Comment by kristianmandrup** [comment]
Yes, please add Vue2 support in a `@next` branch :) Cheers!

**Comment by bajramemini** [comment]
A `@next` branch would be awesome. Just for the time being.

**Comment by dts** [comment]
@kristianmandrup, @HenriqueMatias: There is a @next branch... it just isn't ready for production yet.  If you have time to wrench on it, fix it up and submit a PR!

**Comment by timefordroids** [comment]
Also waiting of Vue 2.0 support :)

**Comment by juppdes** [comment]
@dts How i do to install the next branch ? npm install keen-ui@next is not working...

**Comment by dts** [comment]
Ya gotta do it with git references, but last I checked it wasn't quite ready for use that way (but it's been a week or two, so my memory isn't clear).  So it'd be something like `npm install https://github.com/josephuspaye/keen-ui#next` or something like that.

**Comment by juppdes** [comment]
@dts It worked. thank you friend!

**Comment by kristianmandrup** [comment]
Yeah, guys please all try to add a little something to make it more Vue2 compatible

**Comment by dinfer** [comment]
Hi, does it supports 'runtime-only build'? I got an error.

```js
vue.common.js?4eb4:2611[Vue warn]: You are using the runtime-only build of Vue where the template option is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
(found in component <ui-button>)
```

I'm using [electron-vue](https://github.com/SimulatedGREG/electron-vue), Keen-UI, and just use one component, UiButton.

both [JosephusPaye/Keen-UI#next](https://github.com/JosephusPaye/Keen-UI/tree/next) and [LucasIcarus/Keen-UI#next](https://github.com/LucasIcarus/Keen-UI/tree/next) are used, got the same warning, and nothing is shown on the page.

Then, I change the webpack config like this:

```js
resolve: {
  alias: {
    vue: 'vue/dist/vue.js'
  }
}
```

but i got another error

```
vue.js?b569:2611[Vue warn]: Property or method "$els" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in component <ui-button>)
```

**Comment by timefordroids** [comment]
Hi @dinfer 
I guess you're using Vue 2.x but Keen UI still not ready for it.

**Comment by moxx** [comment]
the branch of Lucaslcarus https://github.com/LucasIcarus/Keen-UI/tree/next is ready for 2.0 so you can get `dist/*` from the branch and replace it in your `./node_modules/keen-ui/dist/`.

**Comment by dinfer** [comment]
thanks a lot ;)

**Comment by kristianmandrup** [comment]
Perhaps publish a v2 version to npm ;)

**Comment by LucasIcarus** [comment]
Hello guys, I update the next branch in my fork repo, and some change has been done.

For now, this still not ready for project using, and to be honestly, I have no any exp in writing docs for any components lib.. The code works fine with Vue2.0 and the docs dosen't. The way to use a component is located its corresponding doc-file in src-docs.

I'm happy to receive any guidences or bug reports with details from you guys about this migration.

**Comment by akirak** [comment]
@LucasIcarus It fails to build due to the upgrade to webpack 2. Does it build in your environment? 

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not matc
h the API schema.
 - configuration has an unknown property 'banner'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?
```

**Comment by LucasIcarus** [comment]
@akirak 

Maybe the version of webpack2 cause this...  I use 2.1.0-beta.22 specifically. I seem met this error message with the latest version of weback.beta for the invalid prop 'vue' before.
I change the corresponding setting in package.json and move the banner attr separatly to `build.js`/`build.min.js`/`lib.js` in the newest pr..

I build all file ok with beta.22 in windows 10 with node 6.9.10..

Hope that will solve this, and can u run the build again, plz?

**Comment by kristianmandrup** [comment]
Yes, the webpack config syntax changed after beta.23. Now it is validated with a strict schema validator! No more custom keys.

Check these links for info on how to upgrade:

https://gist.github.com/sokra/27b24881210b56bbaff7
http://javascriptplayground.com/blog/2016/10/moving-to-webpack-2/

Cheers :)

**Comment by akirak** [comment]
@LucasIcarus Yes, after the latest commit, your package successfully compiles. In order to run `npm run dev`, I had to run `npm run clean:all` in advance, but it seems to work. Thanks.

**Comment by kristianmandrup** [comment]
So it now works with Vue2 and webpack > 2.1.beta23 ?? :)

**Comment by akirak** [comment]
I have used version 2.1.0-beta.22 of webpack.

**Comment by kristianmandrup** [comment]
But it works with latest Vue? :) Great!

**Comment by LucasIcarus** [comment]
@akirak

Now, it fit for latest webpack and vue... test by docs runs fine..

@kristianmandrup

Your links help a lot, thanks..  ٩(๑´3‘๑)۶

**Comment by kristianmandrup** [comment]
@LucasIcarus You are welcome! Try to make it work for .beta.25 it's the new way...

**Comment by LucasIcarus** [comment]
@kristianmandrup 

It's already been done... See through the last pr.

**Comment by zxc23** [comment]
@LucasIcarus I can't use @click or @contextmenu on the UI-Button component. Would that be something I'm doing wrong, or a bug?

**Comment by stbaer** [comment]
@zxc23 - maybe you have to use @click.native if it's vue 2.0.

**Comment by zxc23** [comment]
@stbaer Thanks, that was it. I hadn't heard of .native until now.

**Comment by Jordy-A** [comment]
@JosephusPaye Any news on updating the master? ;)

**Comment by kevbou** [comment]
Hello @LucasIcarus, I encounter this error when using the ui-textbox. As the value prop is not supposed to be mandatory, I guess there is an issue ?

```
[Vue warn]: Missing required prop: "value" 
(found in component <ui-textbox> at C:\C-Code\Keen-UI\src\UiTextbox.vue)
```

Have a good day

**Comment by LucasIcarus** [comment]
@kevbou

The new usage might

```xml
<ui-textbox
    label="Name" name="name" type="text" placeholder="Enter your name"
    v-model="values.value1">
</ui-textbox>
```
The `v-model` turns value prop of component automaticly.

**Comment by kevbou** [comment]
@LucasIcarus great thank you

**Comment by LucasIcarus** [comment]
Close this pr temporarily, for merge some early update from the author. And writing some docs maybe.

**Comment by LucasIcarus** [comment]
@JosephusPaye 

Hello there. I read the last commits in the next branch. The idea of new docs structure and the new build system with gulp v4 is brilliant. What I want to know is your schedule or progress about new components (vue) and new docs (pug, js, styls). So that maybe we can do the update of Keen 1.0 together and avoid duplication of work.

At last, in new doc structure, r u trying to use static vue.min.js from cdn or npm and with some Keen-UI component import in shared.js and ui-*.js and 
```js
new Vue({
    el: '#app'
})
```
in the `src-docs/index.pug` to build it?

**Comment by JosephusPaye** [comment]
@LucasIcarus,

I've made more changes to the build system, switching back to an SPA, but using Vue Router. Pug has been removed and I've switching the styles to Sass, using BEM.

With the number of things I've changed, a merge is probably not feasible at this point. I'll push my changes soon so you can have a look. 

Thanks for all your work on this.

Josephus

**Comment by LucasIcarus** [comment]
@JosephusPaye 

Sounds like that the v1.0 will be finished soon? That's great. Very much looking forward.

**Comment by JosephusPaye** [comment]
Hi @LucasIcarus,

I just pushed my latest changes: https://github.com/JosephusPaye/Keen-UI/commits/next

All the components have be rewritten from scratch to support Vue 2 and have a smaller/more consistent API.

Only thing left is the rest of the documentation, which I hope to complete this week.

Josephus

**Comment by lavezzi1** [comment]
@JosephusPaye Incredible news! Just tried a few components like UiMenu & UiMenuOption on vue 2.1.8 and got this error:
```
Do not use built-in or reserved HTML elements as component id:
```

**Comment by LucasIcarus** [comment]
@JosephusPaye 

Hi, I notice this thrilled update... Hope it can be released offically soon... 

Thanks for this great working!

There are some questions.

Using node_modules to load fuzzysearch and tether-* will cause bug when using Keen-UI in server-side-rendering, these 2 packages are designed for browser using and need `window` and `document`.

Any instruction or plan about unit test? 

Just load your new art, need some time to learn more.  : )

**Comment by JosephusPaye** [comment]
[Keen UI v1.0.0](https://josephuspaye.github.io/Keen-UI/1.0.0/) with support for Vue 2 has now been [released](https://github.com/JosephusPaye/Keen-UI/releases/tag/v1.0.0).

Thanks for your contribution @LucasIcarus, I used some of your code in this release.

**Pull request closed without merging**
