### PR TITLE
UiSlider with minValue and maxValue parameters

### PR DESCRIPTION
**Pull request by stijnvermeeren**
Hi Josephus,

Thanks for your great work on this project.

For my own project, I needed a slider with custom minimal and maximal values. I think it would be useful to include this option in the official project as well. So here's a pull request with my approach. I also updated examples and the parameter list in the docs.

Design decisions made which could be up for discussion:
* What should happen if `minValue >= maxValue`? Vue does not seem to support validation of two props together. In the end, I implemented an automatic fallback to the default values of 0 and 100 in case `minValue >= maxValue`.
* Where should the snap points start if `minValue` is not a multiple of `step`: at `minValue` or at the first multiple of `step`? I went with the second approach, so the docs (_"Setting to true will ensure that the value is always a multiple of the step prop when a drag is completed."_) remain true.
* What should the snap behaviour be if no multiple of `step` lies between `minValue` and `maxValue`? In my implementation, the behaviour in this case is as if `snapToSteps` were deactivated, i.e. you can select any value.

Other minor changes:
* Previously, when setting e.g. `step = 15` and dragging the slider to 95, the slider would snap to 100, even though this is not a multiple of 15. With my code, the `snapToSteps` guarantee in the docs (_"Setting to true will ensure that the value is always a multiple of the step prop when a drag is completed."_) also applies to this case, i.e. the slider will snap to 90.
* `snapToSteps` now also behaves consistently when incrementing/decrementing with the keyboard (relevant if `value` is set to a number that is not a multiple of `step` from outside the component).
* In the slider documentation examples, the "volume" icon is removed from the examples which are not about the icon.
* Corrected the default value for `steps` in the docs from 5 to 10.

I hope you like this contribution. Please do code review and I'll take your points on board where necessary.

PS: for my own project, I am also implementing a fully customisable list of snap points (i.e. not all multiples of the same number). I guess this might be too advanced / too special-purpose to include in your project, but if you're interested, then I'm happy to make a pull request for that as well.

### CODE REVIEW

**Comment by JosephusPaye** [comment]
Hi Stijn,

Thanks for the pull request (and the detailed explanation of your implementation).

Currently I'm busy with study and may not be able to do a proper code review in the next few weeks. However, I intend to do so and get it merged for the next release.

**Comment by stijnvermeeren** [comment]
@JosephusPaye I fixed another small bug where the `onDragStop` would be executed and the `dragend` event would be emitted for _every_ slider on the page, every time the user clicks _anywhere_ on the page. I avoid this by a simple `if (this.isDragging)` check in the `onDragStop` method. Though maybe a cleaner solution would be to only add the `touchend`/`mouseup` event listeners to the document when the user actually starts dragging the slider?

**Comment by JosephusPaye** [comment]
Pretty good 👍. All the design decisions you made make sense.

Only one change, to rename `validatedMinValue` to `moderatedMinValue`, and the same for `validatedMaxValue`, but I'll do this after the merge.

**Comment by JosephusPaye** [comment]
Merged, thanks!

**Comment by JosephusPaye** [comment]
[Updated the docs and change log](https://github.com/JosephusPaye/Keen-UI/commit/19ed6a65bb6bdcad672f336e1085eb50495ea45f), and renamed props to `min` and `max` to match HTML's native  [range slider](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range).

**Pull request merged**
